//! The web UI shell, embedded into the binary so `tare serve` ships a self-contained dashboard with
//! no runtime file dependency (same spirit as the bundled pricing + hero SVG). The asset table is
//! GENERATED at build time by `build.rs`, which walks the committed `assets/ui` tree (the reproducible
//! output of `scripts/build-ui.sh`) and `include_str!`s every text module. A directory walk can't rot,
//! so a newly added module can never 404 the way the old hand-maintained match did.
//!
//! Binary assets (self-hosted WOFF2 fonts) are embedded separately in `UI_BINARY` (`include_bytes!`)
//! and served via `ui_binary_asset` through the proxy's bytes read path — the String read
//! API can't carry bytes. Both tables are generated by `build.rs` and sorted by served path.

// pub static UI_ASSETS: &[(&str, &str, &str)]  — text modules  (served_path, content_type, body)
// pub static UI_BINARY: &[(&str, &str, &[u8])] — binary assets (served_path, content_type, bytes)
// Both sorted by served_path so the lookups can binary-search.
include!(concat!(env!("OUT_DIR"), "/ui_assets_generated.rs"));

/// Resolve a UI asset path (relative to the served `/__tare/` root) to its content type + body.
/// `""` / `"/"` map to the app shell. Returns `None` for anything not in the embedded text set
/// (including binary fonts — see the module note).
pub fn ui_asset(rel: &str) -> Option<(&'static str, &'static str)> {
    let rel = rel.trim_start_matches('/');
    let rel = if rel.is_empty() { "index.html" } else { rel };
    UI_ASSETS
        .binary_search_by(|(path, _, _)| (*path).cmp(rel))
        .ok()
        .map(|i| {
            let (_, ctype, body) = UI_ASSETS[i];
            (ctype, body)
        })
}

/// Resolve a UI asset path to a BINARY asset's content type + bytes (self-hosted WOFF2 fonts).
/// Returns `None` for non-binary paths (which fall through to `ui_asset`). Served through
/// the proxy's bytes read path since the text read API can't carry raw bytes.
pub fn ui_binary_asset(rel: &str) -> Option<(&'static str, &'static [u8])> {
    let rel = rel.trim_start_matches('/');
    UI_BINARY
        .binary_search_by(|(path, _, _)| (*path).cmp(rel))
        .ok()
        .map(|i| {
            let (_, ctype, bytes) = UI_BINARY[i];
            (ctype, bytes)
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn serves_the_shell_and_core_modules() {
        // Empty path → the app shell.
        assert_eq!(
            ui_asset("").map(|(ct, _)| ct),
            Some("text/html; charset=utf-8")
        );
        assert_eq!(
            ui_asset("/").map(|(ct, _)| ct),
            Some("text/html; charset=utf-8")
        );
        assert!(ui_asset("boot.js").is_some());
    }

    #[test]
    fn covers_the_calibrated_bench_modules_the_old_hardcoded_list_missed() {
        // These modules were absent from the old hand-maintained match, breaking `tare serve` boot.
        // The build.rs walk must embed them.
        for path in [
            "ui/icon.js",
            "ui/findBar.js",
            "ui/fonts.css",
            "ui/keymap.js",
            "ui/slashSearch.js",
            "commands/registry.js",
            "shell/rail.js",
            "workspaces/pulse.js",
            "analysis/state.js",
        ] {
            assert!(ui_asset(path).is_some(), "ui_asset must serve {path}");
        }
    }

    #[test]
    fn serves_self_hosted_woff2_fonts_as_binary_with_exact_bytes() {
        // the WOFF2 fonts are embedded as bytes + served with font/woff2, matching disk.
        use std::path::Path;
        let rel = "assets/fonts/files/ibm-plex-mono-latin-400-normal.woff2";
        let (ctype, bytes) = ui_binary_asset(rel).expect("woff2 must be served as a binary asset");
        assert_eq!(ctype, "font/woff2");
        assert!(bytes.starts_with(b"wOF2"), "must be a real WOFF2 payload");
        let on_disk = std::fs::read(
            Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("assets/ui")
                .join(rel),
        )
        .unwrap();
        assert_eq!(
            bytes.len(),
            on_disk.len(),
            "served bytes must match the file on disk"
        );
        assert_eq!(bytes, on_disk.as_slice());
        // A leading slash is tolerated, and a non-binary/unknown path is None (falls through to text).
        assert!(ui_binary_asset(&format!("/{rel}")).is_some());
        assert!(ui_binary_asset("ui/icon.js").is_none());
    }

    #[test]
    fn assigns_content_types_by_extension() {
        assert_eq!(
            ui_asset("ui/fonts.css").map(|(ct, _)| ct),
            Some("text/css; charset=utf-8")
        );
        assert_eq!(
            ui_asset("ui/icon.js").map(|(ct, _)| ct),
            Some("text/javascript; charset=utf-8")
        );
    }

    #[test]
    fn every_committed_text_module_is_served_no_drift() {
        // The build.rs walk is the drift guard: assert the served set matches the js/css/html files on
        // disk under assets/ui, so a future module can never be silently unserved.
        use std::collections::BTreeSet;
        use std::path::Path;
        fn walk(root: &Path, dir: &Path, out: &mut BTreeSet<String>) {
            if let Ok(rd) = std::fs::read_dir(dir) {
                for e in rd.flatten() {
                    let p = e.path();
                    if p.is_dir() {
                        walk(root, &p, out);
                    } else if matches!(
                        p.extension().and_then(|x| x.to_str()),
                        Some("js") | Some("css") | Some("html")
                    ) {
                        out.insert(
                            p.strip_prefix(root)
                                .unwrap()
                                .to_string_lossy()
                                .replace('\\', "/"),
                        );
                    }
                }
            }
        }
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("assets/ui");
        let mut on_disk = BTreeSet::new();
        walk(&root, &root, &mut on_disk);
        let served: BTreeSet<String> = UI_ASSETS.iter().map(|(p, _, _)| p.to_string()).collect();
        assert_eq!(
            served, on_disk,
            "embedded UI assets must match assets/ui text files exactly"
        );
    }
}
