// Generate the embedded UI-asset tables by walking tare-cli/assets/ui at build
// time. TEXT modules (js/css/html) are `include_str!`d into UI_ASSETS `(path, mime, &str)`; BINARY
// assets (self-hosted WOFF2 fonts) are `include_bytes!`d into UI_BINARY `(path, mime, &[u8])`. This
// replaced the old hand-maintained match in ui_assets.rs that silently rotted: 33 UI modules were
// missing, so `tare serve` 404'd on their imports and the browser viewer
// failed to boot. A directory walk can never drift: any committed asset is embedded. Non-served files
// (font license md/txt) are excluded. The binary table is served via the proxy's bytes read path so
// the self-hosted fonts load in the browser viewer (no longer only the system-stack fallback).
use std::env;
use std::fs;
use std::path::Path;

enum Kind {
    Text,
    Binary,
}

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let root = Path::new(&manifest).join("assets/ui");
    // Rebuild the tables whenever the committed assets change (added/removed/edited asset).
    println!("cargo:rerun-if-changed={}", root.display());

    let mut text: Vec<(String, String)> = Vec::new(); // (served-path, absolute-fs-path)
    let mut binary: Vec<(String, String)> = Vec::new();
    walk(&root, &root, &mut text, &mut binary);
    text.sort(); // sorted so ui_asset()/ui_binary_asset() can binary_search by path
    binary.sort();

    let mut code = String::from("// @generated by build.rs from assets/ui — do not edit.\n");
    code.push_str("pub static UI_ASSETS: &[(&str, &str, &str)] = &[\n");
    for (rel, abs) in &text {
        code.push_str(&format!(
            "    ({rel:?}, {mime:?}, include_str!({abs:?})),\n",
            mime = mime_for(rel)
        ));
    }
    code.push_str("];\n");
    code.push_str("pub static UI_BINARY: &[(&str, &str, &[u8])] = &[\n");
    for (rel, abs) in &binary {
        code.push_str(&format!(
            "    ({rel:?}, {mime:?}, include_bytes!({abs:?})),\n",
            mime = mime_for(rel)
        ));
    }
    code.push_str("];\n");

    let out = Path::new(&env::var("OUT_DIR").unwrap()).join("ui_assets_generated.rs");
    fs::write(&out, code).expect("write ui_assets_generated.rs");
}

/// Recurse `dir`, classifying each served asset into `text` (include_str!) or `binary` (include_bytes!).
fn walk(
    root: &Path,
    dir: &Path,
    text: &mut Vec<(String, String)>,
    binary: &mut Vec<(String, String)>,
) {
    let Ok(rd) = fs::read_dir(dir) else { return };
    for entry in rd.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(root, &path, text, binary);
            continue;
        }
        let Some(kind) = kind_of(&path) else { continue }; // skip non-served (md/txt licenses)
        let rel = path
            .strip_prefix(root)
            .unwrap()
            .to_string_lossy()
            .replace('\\', "/"); // forward slashes are the served URL form on every OS
        let abs = path.to_string_lossy().into_owned();
        match kind {
            Kind::Text => text.push((rel, abs)),
            Kind::Binary => binary.push((rel, abs)),
        }
    }
}

/// Served-asset classification by extension. `None` = not served (font license md/txt).
fn kind_of(p: &Path) -> Option<Kind> {
    match p.extension().and_then(|e| e.to_str()) {
        Some("js") | Some("css") | Some("html") => Some(Kind::Text),
        Some("woff2") | Some("woff") => Some(Kind::Binary),
        _ => None,
    }
}

fn mime_for(rel: &str) -> &'static str {
    if rel.ends_with(".css") {
        "text/css; charset=utf-8"
    } else if rel.ends_with(".html") {
        "text/html; charset=utf-8"
    } else if rel.ends_with(".woff2") {
        "font/woff2"
    } else if rel.ends_with(".woff") {
        "font/woff"
    } else {
        "text/javascript; charset=utf-8"
    }
}
